version: "3.4"
services:
  data-transport-layer:
    image: "ethereumoptimism/data-transport-layer:0.5.20"
    restart: unless-stopped
    env_file:
      - ./mainnet/data-transport-layer.env
      - .env
    volumes:
      - "dtl:/db"
    ports:
      - "7878:7878"
  l2geth-replica:
    image: "ethereumoptimism/l2geth:0.5.12"
    restart: unless-stopped
    stop_grace_period: 3m
    entrypoint:
      - /bin/sh
      - "-c"
      - >-
        ./scripts/check-for-chaindata-berlin.sh &&
        ./scripts/l2geth-replica-start.sh
    env_file:
      - ./mainnet/l2geth-replica.env
      - .env
    volumes:
      - "geth:/geth"
      - "./scripts/:/scripts/"
    ports:
      - "9991:8545"
      - "9992:8546"
  replica-healthcheck:
    image: "ethereumoptimism/replica-healthcheck:0.3.11"
    restart: unless-stopped
    env_file:
      - ./mainnet/replica-healthcheck.env
      - .env
    volumes:
      - "./scripts/:/scripts/"
volumes:
  dtl: null
  geth: null
